[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_BASE_URL = "https://vikramreview.netlify.app"
  DATABASE_URL = "postgresql://neondb_owner:npg_bLTZS2YA6zhn@ep-lucky-shape-a1wmu3rk-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"